// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart'
    show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// import 'package:firebase_core/firebase_core.dart';
// import 'firebase_options.dart';

// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzazhFnvyGVGLoWof099IujFYYTJ5asgg',
    appId: '1:678283794658:web:e8a2af72e587bf2eaf26bb',
    messagingSenderId: '678283794658',
    projectId: 'smartpicklocker',
    authDomain: 'smartpicklocker.firebaseapp.com',
    storageBucket: 'smartpicklocker.firebasestorage.app',
    measurementId: 'G-C4GFC48D3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-VjCu7cWzmJd-Yh_9sRwfhot5Ckky_to',
    appId: '1:678283794658:android:1f34241c8c6cf194af26bb',
    messagingSenderId: '678283794658',
    projectId: 'smartpicklocker',
    storageBucket: 'smartpicklocker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIlzN0cj-9UCAQSBnvIKC8ouOiC4ULM1I',
    appId: '1:678283794658:ios:a379007c05c5b2b5af26bb',
    messagingSenderId: '678283794658',
    projectId: 'smartpicklocker',
    storageBucket: 'smartpicklocker.firebasestorage.app',
    iosBundleId: 'com.example.smartPickApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIlzN0cj-9UCAQSBnvIKC8ouOiC4ULM1I',
    appId: '1:678283794658:ios:a379007c05c5b2b5af26bb',
    messagingSenderId: '678283794658',
    projectId: 'smartpicklocker',
    storageBucket: 'smartpicklocker.firebasestorage.app',
    iosBundleId: 'com.example.smartPickApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzazhFnvyGVGLoWof099IujFYYTJ5asgg',
    appId: '1:678283794658:web:a5879f6c860e9cfdaf26bb',
    messagingSenderId: '678283794658',
    projectId: 'smartpicklocker',
    authDomain: 'smartpicklocker.firebaseapp.com',
    storageBucket: 'smartpicklocker.firebasestorage.app',
    measurementId: 'G-E5CVB3YKED',
  );
}
